### ISSUE TITLE
Template Repository화

### ISSUE THREAD

**Issue by NovemberOscar** [JoMingyu/Flask-Large-Application-Example#4]
![image](https://user-images.githubusercontent.com/20695897/61171223-86be7780-a5af-11e9-986f-2abdcc0bb013.png)
깃허브의 Template Repository 기능을 사용할 수 있도록 하면 좋을 것 같네요

**Comment by JoMingyu** [comment]
cookiecutter 사용! template repository가 더 나을까요?

**Comment by NovemberOscar** [comment]
Cookiecutter는 코드의 가독성을 해칠수 있다고 생각되네요

**Comment by JoMingyu** [comment]
template repository로 바꾸는 작업 진행해볼게용
